# Generated by Django 6.0.7 on 2026-07-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(default="General", max_length=100)),
                ("date", models.DateField(blank=True, null=True)),
                ("content", models.TextField()),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="Upload blog image",
                        null=True,
                        upload_to="blogs/",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to static image (optional, e.g. 'images/blog-1.jpg')",
                        max_length=200,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of display (ascending)"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
