# Generated by Django 6.0.7 on 2026-08-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_applicationfield_course_applicationsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_open",
            field=models.BooleanField(
                default=True,
                help_text="Toggle whether applications are currently open or closed for this course.",
                verbose_name="Application Status (Open/Closed)",
            ),
        ),
    ]
