# Generated by Django 6.0.7 on 2026-07-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applicationfield_course_applicationsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationField',
        ),
        migrations.DeleteModel(
            name='ApplicationSubmission',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
