# Generated by Django 6.0.7 on 2026-07-31 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_applicationfield_delete_applicationsubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="The label of the field, e.g. 'Full Name', 'KCSE Mean Grade'", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('email', 'Email'), ('number', 'Number'), ('textarea', 'Long Text')], default='text', help_text='Type of the input field', max_length=50)),
                ('required', models.BooleanField(default=True, help_text='Is this field required?')),
                ('order', models.IntegerField(default=0, help_text='Display order of this field on the application form')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(default='Level 5 & 6', help_text='e.g. Level 5 & 6, Short Course', max_length=100)),
                ('image', models.FileField(blank=True, help_text='Upload course image', null=True, upload_to='courses/')),
                ('image_path', models.CharField(blank=True, help_text="Path to static image (optional, e.g. 'images/perioperative-img.jpg')", max_length=200, null=True)),
                ('application_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Application fee amount', max_digits=10)),
                ('paystack_public_key', models.CharField(blank=True, help_text='Paystack Public Key for payment inline integration', max_length=200, null=True)),
                ('fees_structure_pdf', models.FileField(blank=True, help_text='Upload PDF of the school fees structure', null=True, upload_to='fees/')),
                ('fees_structure_text', models.TextField(blank=True, help_text='Manually write/update the school fees information', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict, help_text='Dynamically filled fields stored as a JSON object')),
                ('paid', models.BooleanField(default=False, help_text='Whether the application fee was successfully paid')),
                ('payment_reference', models.CharField(blank=True, help_text='Paystack transaction reference', max_length=100, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid via Paystack', max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.course')),
            ],
        ),
    ]
