# Generated by Django 6.0.7 on 2026-08-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_is_open'),
        ('core', '0004_applicationfield_course_applicationsubmission'),
    ]

    operations = [
    ]
